FROM ubuntu:22.04

# Avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update package lists and install packages
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    debianutils \
    git \
    jq \
    make \
    net-tools \
    psmisc \
    python3 \
    silversearcher-ag \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app
