FROM alpine:3.19

# Install packages
RUN apk add --no-cache \
    bash \
    curl \
    git \
    iproute2 \
    jq \
    make \
    procps \
    python3 \
    the_silver_searcher \
    unzip \
    which \
    zip \
    && echo "alias netstat='ss'" >> /etc/profile.d/aliases.sh

# Set working directory
WORKDIR /app
